server:
  port: 8082

spring:
  application:
    name: msa-service-coffee-status

  #Config Server
  config:
    import: "optional:configserver:"

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/

